#!/bin/sh

# Urxvt must be executed after the feh. Scripts mimic asynchronous execution,
# where Fluxbox will start whenever any app here will fail.

firefox &
authy &
xrandr --output eDP --brightness 0.4 &

# To enable transparency in urxvt, initiate the wallpaper first and wait for it
# to complete
feh --no-fehbg --bg-scale '/home/robak/.fluxbox/styles/llama/wallpaper'
urxvt &
