#!/bin/sh
# Change your keymap:
# xmodmap "/home/robak/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.

# battery statuc systray icon
cbatticon -l 13 -c 6 &
# notification server
dunst -conf ~/.config/dunst/dunstr &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/robak/.fluxbox/log"
