#!/bin/sh

# Urxvt must be executed after the feh. Scripts mimic asynchronous execution,
# where Fluxbox will start whenever any app here will fail.

firefox &
1password --silent &

# To enable transparency in urxvt, initiate the wallpaper first and wait for it
# to complete
feh --no-fehbg --bg-scale '/home/marcinmanse/.fluxbox/styles/toxic-flowers/wallpaper'
urxvt &
