source-file ~/.tmux/tmux.conf

# Session 0
new-session -s 0_cli -n root
new-window -n cli
# Session 1
setenv -g PROJECT workspace/dotfiles
new-session -s 1_dotfiles -n cli -c workspace/dotfiles
new-window -n vim -c workspace/dotfiles
new-window -n llm -c workspace/dotfiles
select-window -t 1_dotfiles:cli
