source-file ~/.tmux/tmux.conf

# Session 0
new-session -s 0_cli -n root
new-window -n cli1
new-window -n cli2
new-window -n cli3
select-window -t 0_cli:root
# Session 1
new-session -s 1_pomodoro -n pomodoro
new-window -n cli
select-window -t 1_pomodoro:pomodoro
