source-file ~/.tmux/tmux.conf

setenv -g PROJECT ~/workspace/goworld
new-session -s 1_goworld -n cli -c ~/workspace/goworld
new-window -n vim -c ~/workspace/goworld
new-window -n llm -c ~/workspace/goworld
select-window -t 1_goworld:cli
