source-file ~/.tmux/tmux.conf

# Session 0
new-session -s 0_cli -n root
new-window -n cli
# Session 1
setenv -g PROJECT ~/workspace/royaltiz/platform/repo
new-session -s 1_project -n cli -c ~/workspace/royaltiz/platform/repo
new-window -n vim -c ~/workspace/royaltiz/platform/repo
new-window -n llm -c ~/workspace/royaltiz/platform/repo
new-window -n job -c ~/workspace/royaltiz/platform/repo
new-window -n log -c ~/workspace/royaltiz/platform/repo
new-window -n app -c ~/workspace/royaltiz/platform/repo
select-window -t 1_project:cli
