#!/bin/bash
# get lates branches from upstream and delete localy merged branches
git fetch upstream && git checkout upstream/master && git push origin HEAD:master && git delete-merged-branches && git remote update -p && git branch -D master && git checkout -b master && git branch
