# Session 0
new-session -s 0_root
# Session 1
new-session -s 1_terminal
# Session 2
new-session -s 2_dotfiles -n vim -c workspace/dotfiles
new-window -n console -c workspace/dotfiles
select-window -t console
# Session 3
setenv -g PROJECT ~/workspace/goworld
new-session -s 3_repo -n vim -c ~/workspace/goworld
new-window -n console -c ~/workspace/goworld
new-window -n tests -c ~/workspace/goworld
new-window -n deploy -c ~/workspace/goworld
new-window -n logs -c ~/workspace/goworld
select-window -t console
