# Session 0
new-session -s 0_root
# Session 1
new-session -s 1_terminal
# Session 2
new-session -s 2_dotfiles -n vim -c workspace/dotfiles
new-window -n console -c workspace/dotfiles
select-window -t console
# Session 3
setenv -g PROJECT ~/workspace/royaltiz/platform/repo
new-session -s 3_repo -n vim -c ~/workspace/royaltiz/platform/repo
new-window -n console -c ~/workspace/royaltiz/platform/repo
new-window -n tests -c ~/workspace/royaltiz/platform/repo
new-window -n deploy -c ~/workspace/royaltiz/platform/repo
new-window -n logs -c ~/workspace/royaltiz/platform/repo
new-window -n db -c ~/workspace/royaltiz/platform/repo
select-window -t console
# Session 4
setenv -g PROJECT ~/workspace/royaltiz/platform/worktree
new-session -s 4_worktree -n vim -c ~/workspace/royaltiz/platform/worktree
new-window -n console -c ~/workspace/royaltiz/platform/worktree
new-window -n tests -c ~/workspace/royaltiz/platform/worktree
new-window -n deploy -c ~/workspace/royaltiz/platform/worktree
new-window -n logs -c ~/workspace/royaltiz/platform/worktree
new-window -n db -c ~/workspace/royaltiz/platform/worktree
select-window -t console
