#!/bin/bash
# get lates branches from origin and delete localy merged branches
git fetch origin && git checkout origin/master && git push origin HEAD:master && git branch --merged master | grep -v master | xargs -r -n 1 git branch -d && git remote update -p && git branch -D master && git checkout -b master && git branch
