#!/bin/sh

source $HOME/.configitor/abstract.sh

ignore=$HOME/.gitignore
echo "# File generated automatically" > $ignore
echo "" >> $ignore
find $HOME/.configitor -name ignores | xargs cat >> $ignore

if [ -f $ignore ]; then
    git_ignore_lines=`grep -c "" ${ignore}`
fi

if [[ -z $git_ignore_lines ]]; then
    c_error "<configitor> gitignore file composition failed."
elif [ 3 -gt $git_ignore_lines ]; then
    c_info "<configitor> Added ${git_ignore_lines} line to gitignore. Seems to be to less."
else
    c_success "<configitor> Added ${git_ignore_lines} lines to gitignore."
fi
